# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_model', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_city', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_country', models.CharField(blank=True, max_length=50, null=True)),
                ('pro_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('pro_email', models.EmailField(default='', max_length=254)),
                ('op_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('op_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('op_city', models.CharField(blank=True, max_length=100, null=True)),
                ('op_country', models.CharField(blank=True, max_length=50, null=True)),
                ('op_email', models.EmailField(default='', max_length=254)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutTeamImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('img', models.ImageField(blank=True, null=True, upload_to='about')),
                ('fb_url', models.URLField(default='')),
                ('tw_url', models.URLField(default='')),
                ('post_title', models.CharField(blank=True, max_length=100, null=True)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.AboutModel')),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=200, null=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('blog_description', models.TextField(blank=True, null=True)),
                ('blog_detail', models.TextField(blank=True, null=True)),
                ('blog_author', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_thumbnail', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_for', models.CharField(blank=True, choices=[('PC', 'Computer'), ('ANDRIOD', 'Android'), ('WEB', 'Web'), ('OTHERS', 'Others')], max_length=10, null=True)),
                ('spec_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamesDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='games')),
                ('completion_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GamesDownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(choices=[('Play', 'Google PlayStore'), ('Win', 'Universal Windows AppStore'), ('FB', 'Facebook Gameroom'), ('Itch', 'Itch.IO'), ('Smsg', 'Samsung AppStore'), ('Amz', 'Amazon Store')], max_length=4)),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='GamesGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('img_caption', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('released_on', models.DateField()),
                ('game_desc', models.TextField(blank=True, null=True)),
                ('age_rating', models.IntegerField(blank=True)),
                ('single_player', models.BooleanField(default=False)),
                ('multiplayer', models.BooleanField(default=False)),
                ('game_story', models.TextField(blank=True, null=True)),
                ('game_thumbnail', models.ImageField(upload_to='games')),
                ('slide_image', models.ImageField(blank=True, upload_to='games')),
                ('web', models.BooleanField(default=False)),
                ('pc', models.BooleanField(default=False)),
                ('android', models.BooleanField(default=False)),
                ('console', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThanksName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_to_add', models.CharField(blank=True, max_length=200, null=True)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.AboutModel')),
            ],
        ),
        migrations.AddField(
            model_name='gamesgallery',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesModel'),
        ),
        migrations.AddField(
            model_name='gamesdownloadlink',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesModel'),
        ),
        migrations.AddField(
            model_name='gamesdev',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesModel'),
        ),
        migrations.AddField(
            model_name='gamerequirements',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesModel'),
        ),
    ]
