# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0002_gamesmodelpage_indexmodelpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodelpage',
            name='released_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='updated',
            field=models.DateField(),
        ),
    ]
