# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0002_auto_20170823_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pandorastrum.PortfolioModel'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('EXP', 'Experimental'), ('3D', '3d'), ('UNREAL', 'Unreal'), ('UNITY', 'Unity')], max_length=12),
        ),
    ]
