# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0002_blogcontentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.AuthorModel'),
        ),
    ]
