# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0003_auto_20170819_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_detail',
        ),
    ]
