# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0003_auto_20170824_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('EXPERIMENTAL', 'Experimental'), ('CONCEPT', 'Concept'), ('UNREAL', 'Unreal'), ('3D', '3d'), ('UNITY', 'Unity')], max_length=12),
        ),
    ]
