# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0003_auto_20170813_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesmodelpage',
            name='released_on',
            field=models.DateField(),
        ),
    ]
