# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0004_auto_20170813_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodelpage',
            name='android_compatability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='console_compatability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='pc_compatability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='web_compatability',
            field=models.BooleanField(default=False),
        ),
    ]
