# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0004_remove_blogmodel_blog_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontentmodel',
            name='image_full_width',
        ),
        migrations.AddField(
            model_name='blogcontentmodel',
            name='image_size',
            field=models.CharField(choices=[('Full-Width', 'Full-Width'), ('One-Sided', 'One-Sided')], default='', max_length=15),
        ),
    ]
