# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0004_auto_20170826_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesmodel',
            old_name='game_desc',
            new_name='game_short_description',
        ),
        migrations.RenameField(
            model_name='gamesmodel',
            old_name='multiplayer',
            new_name='is_slide_featured',
        ),
        migrations.RemoveField(
            model_name='gamesmodel',
            name='age_rating',
        ),
        migrations.RemoveField(
            model_name='gamesmodel',
            name='game_story',
        ),
        migrations.RemoveField(
            model_name='gamesmodel',
            name='single_player',
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='game_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNREAL', 'Unreal'), ('3D', '3d'), ('CONCEPT', 'Concept'), ('UNITY', 'Unity'), ('EXPERIMENTAL', 'Experimental')], max_length=12),
        ),
    ]
