# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0005_auto_20170819_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='image_size',
            field=models.CharField(choices=[('Full-Width', 'Full-Width'), ('One-Sided', 'One-Sided')], default='One-Sided', max_length=15),
        ),
    ]
