# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0006_auto_20170827_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrequirements',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('BEAT EM UP', 'Beat em up'), ('SPORTS', 'Sports'), ('STRATEGY', 'Strategy'), ('SIMULATION', 'Simulation'), ('MOBA', 'Moba'), ('INFINITE RUNNER', 'Infinite Runner'), ('PUZZLE', 'Puzzle'), ('ADVENTURE', 'Adventure'), ('SPACE', 'Space'), ('PLATFORMER', 'Platformer'), ('3RD PERSON', '3rd Person'), ('ARCADE', 'Arcade'), ('SHOOTING', 'Shooting'), ('HACK N SLASH', 'Hack n slash'), ('ACTION', 'Action'), ('FPS', 'Fps'), ('RPG', 'Rpg'), ('RACING', 'Racing'), ('---', '---'), ('3D', '3d'), ('2D', '2D'), ('TRIVIA', 'Trivia'), ('MMO', 'Mmo')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNREAL', 'Unreal'), ('EXPERIMENTAL', 'Experimental'), ('CONCEPT', 'Concept'), ('3D', '3d'), ('UNITY', 'Unity')], max_length=12),
        ),
    ]
