# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0006_auto_20170813_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesForModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('web_compatability', models.BooleanField(default=False)),
                ('android_compatability', models.BooleanField(default=False)),
                ('pc_compatability', models.BooleanField(default=False)),
                ('console_compatability', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='android_compatability',
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='console_compatability',
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='pc_compatability',
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='web_compatability',
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='age_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='games_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesForModel'),
        ),
    ]
