# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0006_auto_20170819_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentmodel',
            name='image_size',
            field=models.CharField(choices=[('One-Sided', 'One-Sided'), ('Full-Width', 'Full-Width')], default='', max_length=15),
        ),
    ]
