# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0007_auto_20170813_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodelpage',
            name='games_thumbnail',
            field=models.ImageField(null=True, upload_to='games'),
        ),
    ]
