# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0008_gamesmodelpage_games_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesGalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GamesStoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='games_for',
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='games_slider_img',
            field=models.ImageField(null=True, upload_to='slider'),
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='game_title',
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='game_title',
            field=models.ManyToManyField(to='pandorastrum.GamesForModel'),
        ),
        migrations.AddField(
            model_name='gamesmodelpage',
            name='games_gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesGalleryModel'),
        ),
    ]
