# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0009_auto_20170827_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesmodel',
            name='single_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('FPS', 'Fps'), ('ADVENTURE', 'Adventure'), ('PUZZLE', 'Puzzle'), ('PLATFORMER', 'Platformer'), ('ACTION', 'Action'), ('HACK N SLASH', 'Hack n slash'), ('ARCADE', 'Arcade'), ('2D', '2D'), ('STRATEGY', 'Strategy'), ('MMO', 'Mmo'), ('MOBA', 'Moba'), ('RACING', 'Racing'), ('3D', '3d'), ('INFINITE RUNNER', 'Infinite Runner'), ('SPORTS', 'Sports'), ('SIMULATION', 'Simulation'), ('RPG', 'Rpg'), ('---', '---'), ('BEAT EM UP', 'Beat em up'), ('TRIVIA', 'Trivia'), ('SHOOTING', 'Shooting'), ('3RD PERSON', '3rd Person'), ('SPACE', 'Space')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('3D', '3d'), ('CONCEPT', 'Concept'), ('UNITY', 'Unity'), ('UNREAL', 'Unreal'), ('EXPERIMENTAL', 'Experimental')], max_length=12),
        ),
    ]
