# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0010_auto_20170813_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('web_compatability', models.BooleanField(default=False)),
                ('android_compatability', models.BooleanField(default=False)),
                ('pc_compatability', models.BooleanField(default=False)),
                ('console_compatability', models.BooleanField(default=False)),
                ('age_rating', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='gamesstoremodel',
            old_name='game_name',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='age_rating',
        ),
        migrations.RemoveField(
            model_name='gamesmodelpage',
            name='id',
        ),
        migrations.AlterField(
            model_name='gamesmodelpage',
            name='game_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pandorastrum.TypeA'),
        ),
        migrations.DeleteModel(
            name='GamesForModel',
        ),
    ]
