# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0010_auto_20170827_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='current_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamesmodel',
            name='version_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('3RD PERSON', '3rd Person'), ('PUZZLE', 'Puzzle'), ('ADVENTURE', 'Adventure'), ('RPG', 'Rpg'), ('TRIVIA', 'Trivia'), ('ARCADE', 'Arcade'), ('FPS', 'Fps'), ('3D', '3d'), ('SPORTS', 'Sports'), ('2D', '2D'), ('SIMULATION', 'Simulation'), ('SHOOTING', 'Shooting'), ('MMO', 'Mmo'), ('STRATEGY', 'Strategy'), ('PLATFORMER', 'Platformer'), ('HACK N SLASH', 'Hack n slash'), ('MOBA', 'Moba'), ('INFINITE RUNNER', 'Infinite Runner'), ('RACING', 'Racing'), ('BEAT EM UP', 'Beat em up'), ('SPACE', 'Space'), ('---', '---')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNITY', 'Unity'), ('EXPERIMENTAL', 'Experimental'), ('3D', '3d'), ('UNREAL', 'Unreal'), ('CONCEPT', 'Concept')], max_length=12),
        ),
    ]
