# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0011_auto_20170813_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesmodelpage',
            name='game_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pandorastrum.TypeA'),
        ),
        migrations.AlterField(
            model_name='typea',
            name='age_rating',
            field=models.IntegerField(blank=True),
        ),
    ]
