# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0012_auto_20170813_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('web_compatability', models.BooleanField(default=False)),
                ('android_compatability', models.BooleanField(default=False)),
                ('pc_compatability', models.BooleanField(default=False)),
                ('console_compatability', models.BooleanField(default=False)),
                ('age_rating', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gamesmodelpage',
            name='game_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pandorastrum.GamesModel'),
        ),
        migrations.DeleteModel(
            name='TypeA',
        ),
    ]
