# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0014_auto_20170828_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggamesmodel',
            name='business_model',
            field=models.CharField(choices=[('Free To Play', 'Free To Play'), ('Demo/Purchase', 'Demo/Purchase'), ('Online MMO', 'Online MMO')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='upcominggamesmodel',
            name='key_feature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upcominggamesmodel',
            name='rated_for',
            field=models.CharField(choices=[('Teen', 'Teen'), ('Everyone', 'Everyone'), ('Mature', 'Mature'), ('Adult', 'Adult')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='upcominggamesmodel',
            name='teaser_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='upcoming'),
        ),
        migrations.AddField(
            model_name='upcominggamesmodel',
            name='teaser_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='upcoming'),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('SPACE', 'Space'), ('MOBA', 'Moba'), ('ACTION', 'Action'), ('RACING', 'Racing'), ('MMO', 'Mmo'), ('FPS', 'Fps'), ('BEAT EM UP', 'Beat em up'), ('INFINITE RUNNER', 'Infinite Runner'), ('SHOOTING', 'Shooting'), ('SIMULATION', 'Simulation'), ('SPORTS', 'Sports'), ('STRATEGY', 'Strategy'), ('PUZZLE', 'Puzzle'), ('ARCADE', 'Arcade'), ('HACK N SLASH', 'Hack n slash'), ('PLATFORMER', 'Platformer'), ('2D', '2D'), ('---', '---'), ('RPG', 'Rpg'), ('3D', '3d'), ('ADVENTURE', 'Adventure'), ('TRIVIA', 'Trivia'), ('3RD PERSON', '3rd Person')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('CONCEPT', 'Concept'), ('UNREAL', 'Unreal'), ('3D', '3d'), ('EXPERIMENTAL', 'Experimental'), ('UNITY', 'Unity')], max_length=12),
        ),
    ]
