# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0014_auto_20170814_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='game_thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to='games'),
        ),
    ]
