# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0015_auto_20170828_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcominggamesmodel',
            name='dev_stage',
            field=models.CharField(choices=[('Idealization', 'Idealization'), ('Concept Art', 'Concept Art'), ('Story Building', 'Story Building'), ('Programming', 'Programming'), ('3D Modelling', '3D Modeling'), ('2D Sketching', '2D Sketching'), ('Sound Mixing', 'Sound Mixing'), ('Polishing', 'Polishing'), ('Testing QA', 'Testing QA'), ('UI Building', 'UI Building')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('HACK N SLASH', 'Hack n slash'), ('3D', '3d'), ('ARCADE', 'Arcade'), ('SPACE', 'Space'), ('SHOOTING', 'Shooting'), ('MMO', 'Mmo'), ('FPS', 'Fps'), ('PUZZLE', 'Puzzle'), ('STRATEGY', 'Strategy'), ('RACING', 'Racing'), ('SIMULATION', 'Simulation'), ('3RD PERSON', '3rd Person'), ('MOBA', 'Moba'), ('RPG', 'Rpg'), ('ACTION', 'Action'), ('INFINITE RUNNER', 'Infinite Runner'), ('PLATFORMER', 'Platformer'), ('ADVENTURE', 'Adventure'), ('SPORTS', 'Sports'), ('2D', '2D'), ('BEAT EM UP', 'Beat em up'), ('TRIVIA', 'Trivia'), ('---', '---')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNITY', 'Unity'), ('CONCEPT', 'Concept'), ('3D', '3d'), ('EXPERIMENTAL', 'Experimental'), ('UNREAL', 'Unreal')], max_length=12),
        ),
    ]
