# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0015_auto_20170814_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesmodel',
            name='game_thumbnail',
            field=models.ImageField(upload_to='games'),
        ),
    ]
