# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0016_auto_20170815_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
