# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0017_gamesmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='game_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesmodel',
            name='slide_image',
            field=models.ImageField(blank=True, upload_to='games'),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='game_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
