# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0020_gamesgallery_related_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesgallery',
            name='gallery_name',
        ),
    ]
