# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0020_auto_20170828_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('SPACE', 'Space'), ('MOBA', 'Moba'), ('---', '---'), ('SHOOTING', 'Shooting'), ('2D', '2D'), ('TRIVIA', 'Trivia'), ('PLATFORMER', 'Platformer'), ('RACING', 'Racing'), ('ACTION', 'Action'), ('PUZZLE', 'Puzzle'), ('SIMULATION', 'Simulation'), ('SPORTS', 'Sports'), ('HACK N SLASH', 'Hack n slash'), ('STRATEGY', 'Strategy'), ('BEAT EM UP', 'Beat em up'), ('3RD PERSON', '3rd Person'), ('RPG', 'Rpg'), ('INFINITE RUNNER', 'Infinite Runner'), ('FPS', 'Fps'), ('ADVENTURE', 'Adventure'), ('3D', '3d'), ('ARCADE', 'Arcade'), ('MMO', 'Mmo')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('EXPERIMENTAL', 'Experimental'), ('3D', '3d'), ('CONCEPT', 'Concept'), ('UNREAL', 'Unreal'), ('UNITY', 'Unity')], max_length=12),
        ),
    ]
