# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0021_remove_gamesgallery_gallery_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamesDownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(choices=[('Play', 'Google PlayStore'), ('Win', 'Universal Windows AppStore')], max_length=4)),
                ('link', models.URLField(default='')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesModel')),
            ],
        ),
    ]
