# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0021_auto_20170828_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='patreon_link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('PLATFORMER', 'Platformer'), ('MOBA', 'Moba'), ('FPS', 'Fps'), ('3D', '3d'), ('SHOOTING', 'Shooting'), ('TRIVIA', 'Trivia'), ('SPORTS', 'Sports'), ('BEAT EM UP', 'Beat em up'), ('INFINITE RUNNER', 'Infinite Runner'), ('---', '---'), ('ARCADE', 'Arcade'), ('ACTION', 'Action'), ('MMO', 'Mmo'), ('2D', '2D'), ('ADVENTURE', 'Adventure'), ('RACING', 'Racing'), ('PUZZLE', 'Puzzle'), ('SIMULATION', 'Simulation'), ('HACK N SLASH', 'Hack n slash'), ('SPACE', 'Space'), ('STRATEGY', 'Strategy'), ('RPG', 'Rpg'), ('3RD PERSON', '3rd Person')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNREAL', 'Unreal'), ('UNITY', 'Unity'), ('3D', '3d'), ('CONCEPT', 'Concept'), ('EXPERIMENTAL', 'Experimental')], max_length=12),
        ),
    ]
