# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0022_auto_20170829_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('SHOOTING', 'Shooting'), ('---', '---'), ('RPG', 'Rpg'), ('MMO', 'Mmo'), ('PUZZLE', 'Puzzle'), ('BEAT EM UP', 'Beat em up'), ('MOBA', 'Moba'), ('STRATEGY', 'Strategy'), ('2D', '2D'), ('RACING', 'Racing'), ('SPACE', 'Space'), ('3RD PERSON', '3rd Person'), ('SIMULATION', 'Simulation'), ('ADVENTURE', 'Adventure'), ('3D', '3d'), ('HACK N SLASH', 'Hack n slash'), ('INFINITE RUNNER', 'Infinite Runner'), ('ACTION', 'Action'), ('TRIVIA', 'Trivia'), ('PLATFORMER', 'Platformer'), ('SPORTS', 'Sports'), ('FPS', 'Fps'), ('ARCADE', 'Arcade')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='event_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('3D', '3d'), ('UNREAL', 'Unreal'), ('EXPERIMENTAL', 'Experimental'), ('UNITY', 'Unity'), ('CONCEPT', 'Concept')], max_length=12),
        ),
    ]
