# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0022_gamesdownloadlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesdownloadlink',
            name='store_name',
            field=models.CharField(choices=[('Play', 'Google PlayStore'), ('Win', 'Universal Windows AppStore'), ('FB', 'Facebook Gameroom'), ('Itch', 'Itch.IO'), ('Smsg', 'Samsung AppStore'), ('Amz', 'Amazon Store')], max_length=4),
        ),
    ]
