# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0023_auto_20170829_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcontentmodel',
            old_name='attach_banner_here',
            new_name='is_main',
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('2D', '2D'), ('MOBA', 'Moba'), ('3D', '3d'), ('HACK N SLASH', 'Hack n slash'), ('BEAT EM UP', 'Beat em up'), ('SIMULATION', 'Simulation'), ('SPACE', 'Space'), ('---', '---'), ('STRATEGY', 'Strategy'), ('MMO', 'Mmo'), ('SPORTS', 'Sports'), ('ARCADE', 'Arcade'), ('3RD PERSON', '3rd Person'), ('RACING', 'Racing'), ('SHOOTING', 'Shooting'), ('ADVENTURE', 'Adventure'), ('RPG', 'Rpg'), ('PUZZLE', 'Puzzle'), ('FPS', 'Fps'), ('PLATFORMER', 'Platformer'), ('TRIVIA', 'Trivia'), ('INFINITE RUNNER', 'Infinite Runner')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNREAL', 'Unreal'), ('3D', '3d'), ('EXPERIMENTAL', 'Experimental'), ('UNITY', 'Unity'), ('CONCEPT', 'Concept')], max_length=12),
        ),
    ]
