# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0024_gamesdev'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesdev',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='games'),
        ),
    ]
