# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0024_auto_20170829_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_banner',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='blog_description',
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('INFINITE RUNNER', 'Infinite Runner'), ('HACK N SLASH', 'Hack n slash'), ('RACING', 'Racing'), ('BEAT EM UP', 'Beat em up'), ('PLATFORMER', 'Platformer'), ('SIMULATION', 'Simulation'), ('PUZZLE', 'Puzzle'), ('FPS', 'Fps'), ('2D', '2D'), ('SPORTS', 'Sports'), ('RPG', 'Rpg'), ('SPACE', 'Space'), ('TRIVIA', 'Trivia'), ('STRATEGY', 'Strategy'), ('3RD PERSON', '3rd Person'), ('ACTION', 'Action'), ('MMO', 'Mmo'), ('MOBA', 'Moba'), ('SHOOTING', 'Shooting'), ('---', '---'), ('3D', '3d'), ('ARCADE', 'Arcade'), ('ADVENTURE', 'Adventure')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNITY', 'Unity'), ('UNREAL', 'Unreal'), ('3D', '3d'), ('EXPERIMENTAL', 'Experimental'), ('CONCEPT', 'Concept')], max_length=12),
        ),
    ]
