# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0025_gamesdev_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_for', models.CharField(blank=True, choices=[('PC', 'Computer'), ('ANDRIOD', 'Android'), ('WEB', 'Web'), ('OTHERS', 'Others')], max_length=10, null=True)),
                ('spec_details', models.TextField(blank=True, null=True)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.GamesModel')),
            ],
        ),
    ]
