# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0025_auto_20170829_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_freebies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('PUZZLE', 'Puzzle'), ('3D', '3d'), ('---', '---'), ('STRATEGY', 'Strategy'), ('RPG', 'Rpg'), ('MOBA', 'Moba'), ('ARCADE', 'Arcade'), ('ADVENTURE', 'Adventure'), ('ACTION', 'Action'), ('RACING', 'Racing'), ('SPORTS', 'Sports'), ('SIMULATION', 'Simulation'), ('FPS', 'Fps'), ('PLATFORMER', 'Platformer'), ('3RD PERSON', '3rd Person'), ('HACK N SLASH', 'Hack n slash'), ('BEAT EM UP', 'Beat em up'), ('SPACE', 'Space'), ('MMO', 'Mmo'), ('2D', '2D'), ('TRIVIA', 'Trivia'), ('INFINITE RUNNER', 'Infinite Runner'), ('SHOOTING', 'Shooting')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('EXPERIMENTAL', 'Experimental'), ('3D', '3d'), ('CONCEPT', 'Concept'), ('UNREAL', 'Unreal'), ('UNITY', 'Unity')], max_length=12),
        ),
    ]
