# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0026_gamerequirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesmodel',
            old_name='game_background',
            new_name='game_story',
        ),
    ]
