# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0026_auto_20170829_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_dev_talks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='is_game_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='is_tips',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('PLATFORMER', 'Platformer'), ('MMO', 'Mmo'), ('3D', '3d'), ('RPG', 'Rpg'), ('STRATEGY', 'Strategy'), ('HACK N SLASH', 'Hack n slash'), ('2D', '2D'), ('ARCADE', 'Arcade'), ('BEAT EM UP', 'Beat em up'), ('ADVENTURE', 'Adventure'), ('FPS', 'Fps'), ('3RD PERSON', '3rd Person'), ('SPORTS', 'Sports'), ('---', '---'), ('TRIVIA', 'Trivia'), ('MOBA', 'Moba'), ('RACING', 'Racing'), ('SIMULATION', 'Simulation'), ('INFINITE RUNNER', 'Infinite Runner'), ('SHOOTING', 'Shooting'), ('PUZZLE', 'Puzzle'), ('SPACE', 'Space'), ('ACTION', 'Action')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('EXPERIMENTAL', 'Experimental'), ('UNITY', 'Unity'), ('UNREAL', 'Unreal'), ('3D', '3d'), ('CONCEPT', 'Concept')], max_length=12),
        ),
    ]
