# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0027_auto_20170829_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='operation_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='production_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='operation_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='production_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('INFINITE RUNNER', 'Infinite Runner'), ('SHOOTING', 'Shooting'), ('MOBA', 'Moba'), ('MMO', 'Mmo'), ('PUZZLE', 'Puzzle'), ('SIMULATION', 'Simulation'), ('HACK N SLASH', 'Hack n slash'), ('2D', '2D'), ('ARCADE', 'Arcade'), ('FPS', 'Fps'), ('3D', '3d'), ('PLATFORMER', 'Platformer'), ('RPG', 'Rpg'), ('SPACE', 'Space'), ('ADVENTURE', 'Adventure'), ('TRIVIA', 'Trivia'), ('3RD PERSON', '3rd Person'), ('STRATEGY', 'Strategy'), ('SPORTS', 'Sports'), ('BEAT EM UP', 'Beat em up'), ('---', '---'), ('RACING', 'Racing')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNITY', 'Unity'), ('EXPERIMENTAL', 'Experimental'), ('UNREAL', 'Unreal'), ('CONCEPT', 'Concept'), ('3D', '3d')], max_length=12),
        ),
    ]
