# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0028_aboutmodel_aboutteamimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanksName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_to_add', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='operation_address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='operation_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='operation_address3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='operation_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='operation_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='production_address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='production_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='production_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='production_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='production_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thanksname',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pandorastrum.AboutModel'),
        ),
    ]
