# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0028_auto_20170831_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='services_1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='services_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='services_3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='services_4',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('BEAT EM UP', 'Beat em up'), ('---', '---'), ('SIMULATION', 'Simulation'), ('SPORTS', 'Sports'), ('SHOOTING', 'Shooting'), ('TRIVIA', 'Trivia'), ('RACING', 'Racing'), ('HACK N SLASH', 'Hack n slash'), ('3D', '3d'), ('STRATEGY', 'Strategy'), ('2D', '2D'), ('SPACE', 'Space'), ('PLATFORMER', 'Platformer'), ('3RD PERSON', '3rd Person'), ('RPG', 'Rpg'), ('ARCADE', 'Arcade'), ('ACTION', 'Action'), ('FPS', 'Fps'), ('MOBA', 'Moba'), ('INFINITE RUNNER', 'Infinite Runner'), ('MMO', 'Mmo'), ('ADVENTURE', 'Adventure'), ('PUZZLE', 'Puzzle')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('3D', '3d'), ('UNITY', 'Unity'), ('CONCEPT', 'Concept'), ('UNREAL', 'Unreal'), ('EXPERIMENTAL', 'Experimental')], max_length=12),
        ),
    ]
