# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0029_auto_20170816_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='operation_address1',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='operation_address2',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='operation_address3',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='production_address1',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='production_address2',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='operation_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='production_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
