# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0029_auto_20170831_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('---', '---'), ('STRATEGY', 'Strategy'), ('ADVENTURE', 'Adventure'), ('TRIVIA', 'Trivia'), ('MOBA', 'Moba'), ('3RD PERSON', '3rd Person'), ('INFINITE RUNNER', 'Infinite Runner'), ('BEAT EM UP', 'Beat em up'), ('SHOOTING', 'Shooting'), ('ACTION', 'Action'), ('PLATFORMER', 'Platformer'), ('MMO', 'Mmo'), ('RACING', 'Racing'), ('SPACE', 'Space'), ('HACK N SLASH', 'Hack n slash'), ('SIMULATION', 'Simulation'), ('3D', '3d'), ('PUZZLE', 'Puzzle'), ('FPS', 'Fps'), ('ARCADE', 'Arcade'), ('RPG', 'Rpg'), ('SPORTS', 'Sports'), ('2D', '2D')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='game_short_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamesmodel',
            name='game_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homemodel',
            name='event_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('3D', '3d'), ('UNITY', 'Unity'), ('EXPERIMENTAL', 'Experimental'), ('CONCEPT', 'Concept'), ('UNREAL', 'Unreal')], max_length=12),
        ),
    ]
