# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0030_auto_20170816_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='operation_country',
            new_name='op_country',
        ),
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='operation_email',
            new_name='op_email',
        ),
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='production_country',
            new_name='pro_country',
        ),
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='production_email',
            new_name='pro_email',
        ),
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='production_mobile',
            new_name='pro_mobile',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='operation_address',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='production_address',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='op_address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='op_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='op_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='pro_address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='pro_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='pro_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
