# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0030_auto_20170831_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('TRIVIA', 'Trivia'), ('2D', '2D'), ('---', '---'), ('PLATFORMER', 'Platformer'), ('FPS', 'Fps'), ('ARCADE', 'Arcade'), ('RACING', 'Racing'), ('SHOOTING', 'Shooting'), ('MMO', 'Mmo'), ('MOBA', 'Moba'), ('SPACE', 'Space'), ('RPG', 'Rpg'), ('INFINITE RUNNER', 'Infinite Runner'), ('ADVENTURE', 'Adventure'), ('ACTION', 'Action'), ('3RD PERSON', '3rd Person'), ('STRATEGY', 'Strategy'), ('SIMULATION', 'Simulation'), ('PUZZLE', 'Puzzle'), ('3D', '3d'), ('HACK N SLASH', 'Hack n slash'), ('BEAT EM UP', 'Beat em up'), ('SPORTS', 'Sports')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNITY', 'Unity'), ('EXPERIMENTAL', 'Experimental'), ('UNREAL', 'Unreal'), ('CONCEPT', 'Concept'), ('3D', '3d')], max_length=12),
        ),
    ]
