# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0032_auto_20170831_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('Arcade', 'Arcade'), ('Shooting', 'Shooting'), ('Trivia', 'Trivia'), ('Puzzle', 'Puzzle'), ('MMO', 'MMO'), ('FPS', 'FPS'), ('RPG', 'RPG'), ('Racing', 'Racing'), ('Action', 'Action'), ('Beat-em-up', 'Beat-em-up'), ('Driving', 'Driving'), ('2d', '2d'), ('Sports', 'Sports'), ('---', '---'), ('Platformer', 'Platformer'), ('3d', '3d'), ('Infinite Runner', 'Infinite Runner'), ('Strategy', 'Strategy'), ('3rd Person', '3rd Person'), ('Simulation', 'Simulation'), ('Space', 'Space'), ('MOBA', 'MOBA'), ('Hack N Slash', 'Hack N Slash'), ('Adventure', 'Adventure')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('EXPERIMENTAL', 'Experimental'), ('UNREAL', 'Unreal'), ('UNITY', 'Unity'), ('CONCEPT', 'Concept'), ('3D', '3d')], max_length=12),
        ),
    ]
