# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandorastrum', '0034_auto_20170831_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamegenre',
            name='game_genre',
            field=models.CharField(choices=[('Strategy', 'Strategy'), ('Racing', 'Racing'), ('Trivia', 'Trivia'), ('3rd Person', '3rd Person'), ('---', '---'), ('Infinite Runner', 'Infinite Runner'), ('Hack N Slash', 'Hack N Slash'), ('Arcade', 'Arcade'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Action', 'Action'), ('MOBA', 'MOBA'), ('Driving', 'Driving'), ('RPG', 'RPG'), ('Space', 'Space'), ('3d', '3d'), ('Shooting', 'Shooting'), ('2d', '2d'), ('Simulation', 'Simulation'), ('FPS', 'FPS'), ('Sports', 'Sports'), ('MMO', 'MMO'), ('Beat-em-up', 'Beat-em-up'), ('Platformer', 'Platformer')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_caption',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='category_type',
            field=models.CharField(choices=[('UNITY', 'Unity'), ('EXPERIMENTAL', 'Experimental'), ('UNREAL', 'Unreal'), ('CONCEPT', 'Concept'), ('3D', '3d')], max_length=12),
        ),
    ]
